name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  glyphs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            apps/api/package-lock.json
            apps/web/package-lock.json
      - run: node scripts/validate-glyphs.js

  contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            apps/api/package-lock.json
            apps/web/package-lock.json
      - run: node scripts/check-contracts.js

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/api/package-lock.json
      - name: Install API deps (clean)
        run: npm ci
        working-directory: apps/api
      - name: Lint API
        run: npm run lint
        working-directory: apps/api
      - name: Run all tests and guards
        run: npm run test:all
        working-directory: .

  web-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json
      - name: Install web deps
        run: npm ci
        working-directory: apps/web
      - name: Test web (unit)
        run: npm test --silent
        working-directory: apps/web
      - name: Typecheck web
        run: npm run typecheck
        working-directory: apps/web
      - name: Lint web
        run: npm run lint
        working-directory: apps/web
      - name: Build web app
        run: npm run build
        working-directory: apps/web

  e2e:
    runs-on: ubuntu-latest
    env:
      # Port mapping from docker-compose.yml for API
      API_BASE: http://localhost:3388
      # Use a CI-scoped test secret; API will use this via .env injection below
      JWT_SECRET: ${{ secrets.E2E_JWT_SECRET || 'testsecret-ci' }}
      FRONTEND_PORT: '5999'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            apps/web/package-lock.json
      - name: Install web deps
        run: npm ci
        working-directory: apps/web
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: apps/web
      - name: Create .env for CI
        run: |
          cat > .env <<EOF
          POSTGRES_USER=blog
          POSTGRES_PASSWORD=blogpw
          POSTGRES_DB=blog
          POSTGRES_PORT=5433
          JWT_SECRET=${JWT_SECRET}
          CORS_ORIGIN=http://localhost:${FRONTEND_PORT}
          PUBLIC_BASE_URL=${API_BASE}
          NUXT_PUBLIC_API_BASE=${API_BASE}
          EOF
      - name: Start docker services (db, api)
        run: |
          docker compose up -d db api
      - name: Wait for API to be ready
        run: |
          for i in {1..60}; do
            if curl -fsS ${API_BASE}/api/posts > /dev/null; then echo "API up"; exit 0; fi
            sleep 2
          done
          echo "API did not become ready in time"; docker compose logs api; exit 1
      - name: Run E2E tests
        run: npm run test:e2e
        working-directory: apps/web
      - name: Teardown docker
        if: always()
        run: docker compose down -v
