name: Build and Push Docker Images

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  DOCKER_NS: ava2016

jobs:
  build-and-push:
    name: Build and push multi-arch images
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        app: [web, api]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute tags
        id: vars
        run: |
          TAG=${GITHUB_REF_NAME}
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "image=${{ env.DOCKER_NS }}/glyph-${{ matrix.app }}" >> "$GITHUB_OUTPUT"

      - name: Build and push ${{ matrix.app }}
        uses: docker/build-push-action@v6
        with:
          context: apps/${{ matrix.app }}
          file: apps/${{ matrix.app }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.tag }}
            ${{ steps.vars.outputs.image }}:latest
          cache-from: type=registry,ref=${{ steps.vars.outputs.image }}:buildcache
          cache-to: type=registry,ref=${{ steps.vars.outputs.image }}:buildcache,mode=max
